project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

website:
  # title: "SatCamp 2023"
  navbar:
    logo: images/SatCampLogo_White.png
    left:
      - href: index.qmd
        text: Home
      # - home.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
