project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

website:
  title: "SatCamp 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



